// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ArrayGPU")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("F# quotation to OpenCL translator.")>]
[<assembly: AssemblyVersionAttribute("1.1.3")>]
[<assembly: AssemblyFileVersionAttribute("1.1.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ArrayGPU"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyDescription = "F# quotation to OpenCL translator."
    let [<Literal>] AssemblyVersion = "1.1.3"
    let [<Literal>] AssemblyFileVersion = "1.1.3"
