// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.OpenCL.Extensions")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("1.5.6")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-11-08T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("1.5.6")>]
[<assembly: AssemblyInformationalVersionAttribute("1.5.6")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","a7be26ce329053159b6dbc5105623a08a3bcc60e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.OpenCL.Extensions"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "1.5.6"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-11-08T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "1.5.6"
    let [<Literal>] AssemblyInformationalVersion = "1.5.6"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "a7be26ce329053159b6dbc5105623a08a3bcc60e"
