// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("YC.OpenCL.NET")]
[assembly: AssemblyProduct("Brahma.FSharp")]
[assembly: AssemblyVersion("2.0.0")]
[assembly: AssemblyMetadata("ReleaseDate","2021-11-26T00:00:00.0000000+03:00")]
[assembly: AssemblyFileVersion("2.0.0")]
[assembly: AssemblyInformationalVersion("2.0.0")]
[assembly: AssemblyMetadata("ReleaseChannel","alpha9")]
[assembly: AssemblyMetadata("GitHash","17f05e40eac8cda8b7bec37f4db25f14189e2600")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "YC.OpenCL.NET";
        internal const System.String AssemblyProduct = "Brahma.FSharp";
        internal const System.String AssemblyVersion = "2.0.0";
        internal const System.String AssemblyMetadata_ReleaseDate = "2021-11-26T00:00:00.0000000+03:00";
        internal const System.String AssemblyFileVersion = "2.0.0";
        internal const System.String AssemblyInformationalVersion = "2.0.0";
        internal const System.String AssemblyMetadata_ReleaseChannel = "alpha9";
        internal const System.String AssemblyMetadata_GitHash = "17f05e40eac8cda8b7bec37f4db25f14189e2600";
    }
}
