// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.OpenCL.AST")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-04-08T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha9")>]
[<assembly: AssemblyMetadataAttribute("GitHash","2abdfbc791a309f25e47a215aefa498f580a81d3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.OpenCL.AST"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-04-08T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
    let [<Literal>] AssemblyInformationalVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha9"
    let [<Literal>] AssemblyMetadata_GitHash = "2abdfbc791a309f25e47a215aefa498f580a81d3"
