// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.OpenCL.Core")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-19T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha6")>]
[<assembly: AssemblyMetadataAttribute("GitHash","28276e9825423ca1b4530d33e81b02c44fad4269")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.OpenCL.Core"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-19T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
    let [<Literal>] AssemblyInformationalVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha6"
    let [<Literal>] AssemblyMetadata_GitHash = "28276e9825423ca1b4530d33e81b02c44fad4269"
