// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.OpenCL.Core")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-01-27T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","329ab18dbaa9a0ecb6b0b14174eb805b68708e2f")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.OpenCL.Core"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-01-27T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
    let [<Literal>] AssemblyInformationalVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "329ab18dbaa9a0ecb6b0b14174eb805b68708e2f"
